User gcc-9 instead of gcc-10 to fix compile error of RPI.GPIO
    /usr/bin/ld: build/temp.linux-aarch64-3.9/source/py_pwm.o:/tmp/pip-install-j
zxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.h:36: multiple d
efinition of `pin_to_gpio_rev3'; build/temp.linux-aarch64-3.9/source/common.o:/t
mp/pip-install-jzxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.
h:36: first defined here
    /usr/bin/ld: build/temp.linux-aarch64-3.9/source/py_pwm.o:/tmp/pip-install-j
zxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.h:35: multiple d
efinition of `pin_to_gpio_rev2'; build/temp.linux-aarch64-3.9/source/common.o:/t
mp/pip-install-jzxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.
h:35: first defined here
    /usr/bin/ld: build/temp.linux-aarch64-3.9/source/py_pwm.o:/tmp/pip-install-j
zxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.h:34: multiple d
efinition of `pin_to_gpio_rev1'; build/temp.linux-aarch64-3.9/source/common.o:/t
mp/pip-install-jzxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.
h:34: first defined here
    /usr/bin/ld: build/temp.linux-aarch64-3.9/source/py_pwm.o:/tmp/pip-install-j
zxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.h:33: multiple d
efinition of `gpio_mode'; build/temp.linux-aarch64-3.9/source/common.o:/tmp/pip-
install-jzxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/common.h:33: f
irst defined here
    /usr/bin/ld: build/temp.linux-aarch64-3.9/source/soft_pwm.o:/tmp/pip-install
-jzxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/soft_pwm.c:28: multip
le definition of `threads'; build/temp.linux-aarch64-3.9/source/event_gpio.o:/tm
p/pip-install-jzxnv27y/rpi-gpio_7da830c4ed1c47c1bfb884b6ff09f857/source/event_gp
io.c:60: first defined here
    collect2: error: ld returned 1 exit status
    error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1

Signed-off-by: Dongjin Kim <tobetter@gmail.com>